### ISSUE TITLE
Profile name not actually being used

### ISSUE THREAD

**Issue by elison-chen** [awslabs/aws-greengrass-group-setup#10]
Looks like GroupCommands accepts a profile_name parameter, but afterwards it never uses it.

_get_iot_session function also takes in a profile_name as a parameter, but no usages of this function actually pass in the profile_name.

This should be remedied so that people can pass in different profiles to edit/create Greengrass groups in different accounts.

The current work around is to change the default in ~/.aws/credentials depending on which account you want to modify.

**Comment by brettf** [comment]
@elison-chen Although I know it has been some time, I wanted you to know this has been resolved. Please validate that your needs around using AWS CLI `profile` values work.

**Comment by Sandmania** [comment]
Hmm, this doesn't seem to work. Things get created to the default profile even though `--profile-name` is provided with `gg_group_setup create-core`
