### ISSUE TITLE
clean does not work

### ISSUE THREAD

**Issue by neelmitra** [awslabs/aws-greengrass-group-setup#17]
--clean-all doesnot work properly. We still need to do a --clean-file prior to the next run.

**Comment by brettf** [comment]
Can you please provide more details? I've not had this experience. What content specifically is left behind when executing `--clean-all` before executing `--clean-file`?

**Comment by brettf** [comment]
OK - I just did 
````
gg_group_setup create-core
gg_group_setup create
gg_group_setup clean-all
````
..and everything is clean. When you run into the issue again, can you capture any more tidbits and facts and please let me know? Thanks.
