### ISSUE TITLE
How to download the Greengrass software?

### ISSUE THREAD

**Issue by krmrn42** [awslabs/aws-greengrass-group-setup#18]
Greetings,

I'm working on Greengrass deployment automation and have created a script similar to this one (didn't know it existed when I started). And now I found that I cannot find any Greengrass software download links in the documentation. Do you know of any way to download the software without having to create the group and core using AWS Console?

Thank you,
Shavkat

**Comment by krmrn42** [comment]
I think I'll need to redistribute the package as all links that I can find are signed and temporary.

**Comment by brettf** [comment]
Yes - currently you need to download the packages for your project form the console by following these instructions. https://docs.aws.amazon.com/greengrass/latest/developerguide/gg-config.html
Once downloaded you would then host in your own location for your automation.
