### ISSUE TITLE
incompatible with recent awscli versions

### ISSUE THREAD

**Issue by CptnKirk** [awslabs/aws-greengrass-group-setup#4]
It seems the botocore version pulled in by gg_group_setup (via boto3) is botocore-1.5.95.  
The latest awscli package seems to want botocore-1.7.0.

With the old botocore the new cli barfs with:
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/home/jim/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 35, in <module>
    from awscli.help import ProviderHelpCommand
  File "/home/jim/.local/lib/python2.7/site-packages/awscli/help.py", line 27, in <module>
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/home/jim/.local/lib/python2.7/site-packages/awscli/clidocs.py", line 18, in <module>
    from botocore.utils import is_json_value_header
ImportError: cannot import name is_json_value_header

**Comment by brettf** [comment]
@CptnKirk I had some time and tested this today. I started from a clean install of `pip install gg-group-setup` and the `gg_group_setup` command seems to work. Can you please provide some more specific steps, so that I might reproduce the issue you experienced?

**Comment by CptnKirk** [comment]
Clean install is fine with gg_setup. Now install awscli in the same env. This will upgrade botocore. This *might* be ok. However, now reinstall gg_setup. This will downgrade botocore and break awscli. The problem was with gg_setup install breaking awscli. 
- Jim

**Comment by brettf** [comment]
In my recent update to include the `create-core` command I have shifted to `boto3>=1.4.7` as a dependency. Please check to let me know if there remain any issues. Otherwise I'll assume the shift to the latest `boto3` resolves the issue. Thank you.

**Comment by brettf** [comment]
I've no longer been able to recreate this issue. Closing. Please comment with recreation steps if experienced when using the latest version.
